### ISSUE TITLE
Good idea, but...

### ISSUE THREAD

**Issue by HyperMan19680** [InfinityRaider/3DManeuverGear#1]
I'm having a bit of trouble loading blades on my handles. I Ctrl Left/Right click, but no visual showing of the blades. Does it matter if I'm in Creative Mode while doing this?

**Comment by InfinityRaider** [comment]
Are there blades in your holster?

**Comment by HyperMan19680** [comment]
Yes, there are.

**Comment by HyperMan19680** [comment]
I just noticed something else. In the tooltip for the handles, it shows Right blades twice.

**Comment by InfinityRaider** [comment]
I'm gna add some debug statements and give you a new version so I can pinpoint where it goes wrong.

**Comment by HyperMan19680** [comment]
Okay.

**Comment by InfinityRaider** [comment]
Actually to what do you have your sprint hotkey bound?
It's not really ctrl I search for but whatever the sprint hotkey is bound to, apologies.

**Comment by HyperMan19680** [comment]
I don't have it bound, due to another mod I had.

**Comment by InfinityRaider** [comment]
Bind it to something and try that key.

**Comment by HyperMan19680** [comment]
Its working now. My bad. ^_^;
