### ISSUE TITLE
Game crashes when you die, related to your bauble wrapper in 1.10

### ISSUE THREAD

**Issue by xiaoschannel** [InfinityRaider/3DManeuverGear#10]

**Comment by InfinityRaider** [comment]
Don't report crashes without providing a fukcing crash log....

**Comment by xiaoschannel** [comment]
here it is with clean install of forge 2114 and mod 0.10. NOTE: sometimes you only get "disconnected" from the local server (yes, SSP), but sometimes game also crash, and when it does, this is what you get:
(to me seems like you called bauble with a null pointer just btw)

http://pastebin.com/qVk2EhEt

**Comment by InfinityRaider** [comment]
Tx for the crash log, next time use pastebin for posting logs, keeps the issue tracker clean.
I did it for you this time.

**Comment by InfinityRaider** [comment]
Okay, all this code is redundant, I updated baubles, and it now has syncing functionality itself, no longer needed for me to sync the baubles manually.
