### ISSUE TITLE
Crash with version 0.3.0

### ISSUE THREAD

**Issue by Guardian9978** [InfinityRaider/3DManeuverGear#11]
I started up my dedicated server with just this mod and its dependencies and the server crashes with this error:
http://pastebin.com/dTW3WiGs

MC Version: 1.10.2
Forge Version: 12.18.3.2185
Baubles Version: 1.3.8
3D Maneuver Gear Version: 0.3.0
infinitylib Version: 0.3.0

**Comment by InfinityRaider** [comment]
That's a weird crash, I think its because I forgot to set the dependency, thanks for reporting this.

**Comment by InfinityRaider** [comment]
Closing as 1.16 is the active version, previous versions are no longer supported.
