### ISSUE TITLE
Cannot Equip Blades [MC 1.7.10]

### ISSUE THREAD

**Issue by Raptor22a** [InfinityRaider/3DManeuverGear#16]
Using Baubles 1.7.10-1.0.1.10 and 3D Maneuver Gear 1.7.10-0.6, pressing ctrl + rmb/lmb does not equip blades. Blades are in inventory and the blade holsters, however it does not equip the blades.

**Comment by InfinityRaider** [comment]
Closing as 1.16 is the active version, previous versions are no longer supported.
