### ISSUE TITLE
Crash to Desktop upon Acquiring 3D Manuever Gear

### ISSUE THREAD

**Issue by b-wright2501** [InfinityRaider/3DManeuverGear#17]
https://pastebin.com/A4hL5y6w

**Comment by InfinityRaider** [comment]
Some more information would be useful, when does this happen exactly?

**Comment by b-wright2501** [comment]
When trying to spawn the 3D Maneuver gear in creative. In survival I cannot even craft all of the components, and they have an older texture that doesn't look like the ones shown in the recipes. I have reinstalled minecraft, reinstalled all my mods, and others on the server I run with the exact same mod installation can use them just fine.

**Comment by InfinityRaider** [comment]
It's giving a NullPointerException where it shouldnt really be possible.
I don't think its related, but try without Optifine.

**Comment by b-wright2501** [comment]
[https://youtu.be/yiT5uIfLyoc](url) with optifine turned off, same crash.

**Comment by InfinityRaider** [comment]
I expected that but wanted to rule it out to be sure.
Some mod is adding a mixing somewhere (from the stack trave: re:classloading,re:mixin}) which breaks things in an unexpected way.

Unfortunately there is little I can do here, so you will have to try to find out which mod that it is and also report this to them.

**Comment by InfinityRaider** [comment]
It is especially odd that it happens only to you. Are you using any client side mods that your friends aren't using?

**Comment by InfinityRaider** [comment]
I have added a null check to InfinityLib in [this commit](https://github.com/InfinityRaider/InfinityLib/commit/340ded060c18cecd90d2ccc7b5a9d1646d43fb9b), this will prevent it from crashing, but things might not work correctly.
If things break, report this to computing frames as well (they are the ones mixing code in there), perhaps they might have some better insights as to what is happening.
