### ISSUE TITLE
Manuver Gear has no effect after teleporting with RFtools teleporters until you go to main menu and go back in.

### ISSUE THREAD

**Issue by sorgan71** [InfinityRaider/3DManeuverGear#18]

**Comment by InfinityRaider** [comment]
Does this only happen when changing dimensions, or does this also happen when you tp inside the same dimension?

**Comment by sorgan71** [comment]
It happens between nether and overworls, I dont know if that causes it. Just so you know my modslist is absurd so it may not be that. Just so you know I also have the travellers backpack equiped and that may be causing the issue. I have like 30 mods installed so I'm in no place to be suprised there are bugs. Im suprised however that his is the first issue I've had after about 100 hours Playing with the mod though. Really good job on bugfixes.

**Comment by InfinityRaider** [comment]
No, when you mentioned teleporting, an alarm went off in the back of my head that I might have forgotten to handle dimension changing. I asked just to make sure something weird wasn't happening within the same dimension.

If I am correct, the same thing should also happen by simply stepping through a nether or end portal.

**Comment by sorgan71** [comment]
Ok, so you are correct. I had immersive portals on which prevented me from seeing a non rftools example of it until I went from end->overworld which is not a portal affected by immersive portals. For me, any dimension change with a loading screen causes the same issue. The shift + space jump also does not work.

**Comment by InfinityRaider** [comment]
Yes because my code does not realize you have the gear equipped.

When you change dimensions, a new player instance is created and data copied over. I stupidly forgot to copy over the stored data indicating that maneuver gear is equipped, should be a straightforward fix.

In the meantime, you can also take off the gear and put it on again as a workaround until I release a patch.

**Comment by sorgan71** [comment]
Ok, I'll do that. Much more convenient than exiting and re loading.Thanks!

**Comment by InfinityRaider** [comment]
I will upload a release with the fix on CurseForge shortly.
Quite an important fix, as the 3DMG is basicly made for navigating the nether.
