### ISSUE TITLE
Crash in new world menu...?

### ISSUE THREAD

**Issue by Iashar** [InfinityRaider/3DManeuverGear#19]
I was creating a new world, and was going to name it Onyx, but when I hit the X key, the game freaked out, said saving world and CTD. Here's a crash report!
https://pastebin.com/MpDPFkuT
And most relevant part of latest.log
https://pastebin.com/ixY1nAFb
Hope this is somehow helpful! If not, please disregard :)
And yes, it may be one of my many mods conflicting.... But it could be useful!

**Comment by InfinityRaider** [comment]
Yes major fuck up on my part, going to need to fix this asap.

**Comment by Iashar** [comment]
Yay, I'm helpful!
