### ISSUE TITLE
NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Camohunter7t** [InfinityRaider/3DManeuverGear#20]
3dmaneuverGear version 2.0.1
Mc version 1.16.5

Crash Log:
https://paste.ee/p/cPeIr

While playing on a server, as soon as someone created the hand grips, one person's game crashed. Later another person's game crashed. See crashlog

**Comment by InfinityRaider** [comment]
Two times the same crash log?

**Comment by Camohunter7t** [comment]
Multiple players on the server were getting the same error of java.lang.NullPointerException: Ticking entity with the cause being 3dmaneuver
