### ISSUE TITLE
Game crash when grabbing the 3d Maneuvering Gear

### ISSUE THREAD

**Issue by Assasingus14** [InfinityRaider/3DManeuverGear#21]
when I was spawning the 3D maneuvering gear to test my modpack, as i clicked the item in the creative menu the game crashed.

Here are 2 crash logs

[crash-2021-02-18_09.42.37-client.txt](https://github.com/InfinityRaider/3DManeuverGear/files/6006035/crash-2021-02-18_09.42.37-client.txt)

[crash-2021-02-18_09.34.41-client.txt](https://github.com/InfinityRaider/3DManeuverGear/files/6006036/crash-2021-02-18_09.34.41-client.txt)

**Comment by InfinityRaider** [comment]
Try removing Computing Frames and check if that still happens.

**Comment by InfinityRaider** [comment]
I have added a null check to InfinityLib in [this commit](https://github.com/InfinityRaider/InfinityLib/commit/340ded060c18cecd90d2ccc7b5a9d1646d43fb9b), this will prevent it from crashing, but things might not work correctly.
If things break, report this to computing frames as well (they are the ones mixing code in there), perhaps they might have some better insights as to what is happening.
