### ISSUE TITLE
Game crashes when belt is clicked

### ISSUE THREAD

**Issue by Starwarsyeeeet** [InfinityRaider/3DManeuverGear#22]
I was putting some mods together for fun and came across this. I was trying to get it in creative inventory when the game crashed. I kept trying and it still happened. I have curious API and bountiful baubles installed.

Crash report:
[crash-2021-02-28_12.00.49-client.txt](https://github.com/InfinityRaider/3DManeuverGear/files/6057340/crash-2021-02-28_12.00.49-client.txt)

**Comment by InfinityRaider** [comment]
Can you find out what mod adds this computing_frames mixin?
re:computing_frames,re:mixin,re:classloading

**Comment by Starwarsyeeeet** [comment]
Tried it on its own and it still happens.

Crash report:
[crash-2021-02-28_17.59.15-client.txt](https://github.com/InfinityRaider/3DManeuverGear/files/6058337/crash-2021-02-28_17.59.15-client.txt)

**Comment by InfinityRaider** [comment]
Thank you

**Comment by InfinityRaider** [comment]
It might be because it is 1.16.5, and I developed against 1.16.4.
I will update my dev environment and perhaps then I can pinpoint the issue as I have been unable to reproduce this.

**Comment by arBorghi** [comment]
I'm having the same issue. Playing on 1.16.5 & Forge 36.0.46
Edit: I tried it just with the mod and it's dependencies but still crashes.
[crash-2021-03-12_21.39.37-client (3D Maneuver).txt](https://github.com/InfinityRaider/3DManeuverGear/files/6133776/crash-2021-03-12_21.39.37-client.3D.Maneuver.txt)

**Comment by InfinityRaider** [comment]
Ye, i still haven't gotten around to fixing this, apologies.
Also for future reference, don't give me stacktraces with Optifine.

**Comment by InfinityRaider** [comment]
@Starwarsyeeeet @arBorghi 
I have been unable to reproude this, even after updating to 1.16.5.
I have therefore built an InfinityLib jar with additional checks (it will still crash, but it should give more information): https://github.com/InfinityRaider/InfinityLib/releases/download/Debug/Infinitylib-2.0.1-debug.jar

Could either (or both) of you please try running it with that build and giving me the crash report once more?

**Comment by arBorghi** [comment]
> @Starwarsyeeeet @arBorghi
> I have been unable to reproude this, even after updating to 1.16.5.
> I have therefore built an InfinityLib jar with additional checks (it will still crash, but it should give more information): https://github.com/InfinityRaider/InfinityLib/releases/download/Debug/Infinitylib-2.0.1-debug.jar
> 
> Could either (or both) of you please try running it with that build and giving me the crash report once more?

Of course!
[3D Maneuver crash.log](https://github.com/InfinityRaider/3DManeuverGear/files/6137868/3D.Maneuver.crash.log)

**Comment by InfinityRaider** [comment]
Thanks, this is useful information, I will dig deeper now.
I might give you a new debug version in a few days.

**Comment by InfinityRaider** [comment]
I have managed to trace the issue down to it's cause, I still do not understand why it is happening, but I have rewritten the code in order that it should no longer happen.
If a null Capability still does occur, it will no longer crash, but print warnings in the log instead, this may or may not result in loss of some functionality though.
