### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by prodkid** [InfinityRaider/3DManeuverGear#7]
Hi, when I find the item on the creative inventory, it crashes
http://pastebin.com/AKdp2LiR

**Comment by InfinityRaider** [comment]
Remove Optifine and see if it still crashes.

**Comment by prodkid** [comment]
Ah, removing optifine does stop the crashing.

**Comment by InfinityRaider** [comment]
Optifine is too intrusive to support, so i cant support it, sry
