### ISSUE TITLE
Crash 1.10.2 MAKES UNUSABLE!

### ISSUE THREAD

**Issue by DanHolli** [InfinityRaider/3DManeuverGear#8]
crashes of viewing handles weather in JEI, Creative Inventory, or the item itself
**_MAKES THIS MOD UNUSEABLE!!!!!!!!!!**_

**Comment by InfinityRaider** [comment]
You know what, stop shouting and give me a crash report.

**Comment by DanHolli** [comment]
I caps were to add emphasis
will re add mod and give crash report tomorrow

**Comment by DanHolli** [comment]
[link to the crash logs](https://www.dropbox.com/sh/6yjzoju1j3olg31/AABMz5BjgRm8hiSE_QhrV0Z9a?dl=0)

**Comment by DanHolli123** [comment]
sorry work got in the way

**Comment by InfinityRaider** [comment]
A lot of those crashes don't even mention this mod in the stack trace.
Give me a pastebin of the relevant stacktrace please.

**Comment by DanHolli123** [comment]
OK will do ASAP

**Comment by DanHolli** [comment]
[pastebin](http://pastebin.com/jahV0eZC)
[or text file download](https://github.com/InfinityRaider/3DManeuverGear/files/389303/crash-2016-07-21_22.39.30-client.txt)

**Comment by InfinityRaider** [comment]
Try without Optifine.

**Comment by DanHolli** [comment]
Will do even though the game barely runs without Optifine
and I only happens with the handles whether It's in JEI, item drop, or inventory

**Comment by InfinityRaider** [comment]
does it happen without optifine?

**Comment by DanHolli** [comment]
It works fine by its self

**Comment by InfinityRaider** [comment]
I can't really make it work with optifine, it is to intrusive. 
My apologies

**Comment by DanHolli** [comment]
it's only an error rendering the item

**Comment by InfinityRaider** [comment]
Yes and I cant put Optifine in my dev env and the stack trace doesn't tell me anything useful.
